---
abstract: 'Append to TAP output'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Log::Log4perl: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Log4perl-Appender-TAP
requires:
  Log::Log4perl: 0
  Test::Builder::Module: 0
  perl: v5.10.0
resources:
  bugtracker: https://github.com/plicease/log-log4perl-appender-tap/issues
  homepage: http://perl.wdlabs.com/Log-Log4perl-Appender-TAP/
  repository: git://github.com/plicease/log-log4perl-appender-tap.git
version: 0.01
